language: node_js
node_js:
  - "0.10"

before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g bower karma grunt-cli jshint
  - npm install -g bower
  - npm install
  - bower install

script:
  - npm test

notifications:
  - email: false

sudo: false